### PR TITLE
Lab update 5/4

### PR DESCRIPTION
**Pull request by fusinstruments**
Fix keyboard jogging bug, fix y axis left and right discrepancy. Accept master branch yaml file version.

### CODE REVIEW

**Comment by fusinstruments** [comment]
@Isaiah7579 can you review the contents of the yaml file? We ran into some merge conflicts and accepted the master branch's yaml file

**Comment by Isaiah7579** [comment]
The settings we need for the expo are the ones in my last pull request. Me and axel spent a good amount of time calibrating them so the signal appears on the screen as clearly as possible without changing any settings.  Is there a way to go back and accept my default.yaml instead?

**Review by Isaiah7579 — APPROVED** [review]

**Comment by Isaiah7579** [comment]
Nevermind, I took another look at the default.yaml and it seems to have all the important settings I changed

**Comment by adam-smashr** [comment]
Sorry, I could've been more clear. We took your default.yaml. I should've seen that there aren't any changes being made to that file in the file's changed tab. Thanks for the review!

**Pull request merged**
